### PR TITLE
Various bugfixes, round 5

### PR DESCRIPTION
**Pull request by cerna**
This pull request solves various smallish bugs found in the code:

- Build `HM_PCI` module and various other shared libraries under the flag `HAS_SYS_IO` (reported in #267)
- Update no longer valid links in README to current ones

### CODE REVIEW

**Comment by zultron** [comment]
I was added to the org with the intent to make me a Maintainer, but I haven't been able to merge PRs or close out (other users') issues.  Can someone with the necessary privs take a look?

**Comment by zultron** [comment]
BTW, thanks for cleaning up after my mess on this one!

**Comment by luminize** [comment]
Hi John,
I’ll have a look at that.

**Comment by luminize** [comment]
John, you should be able to merge PR's, would you try out if you actually can

**Comment by zultron** [comment]
Thanks, @luminize!  Whatever you did worked.

**Pull request merged**
