### PR TITLE
DO NOT MERGE - CMake alternative

### PR DESCRIPTION
**Pull request by kinsamanka**
Continuation of #246

### CODE REVIEW

**Comment by kinsamanka** [comment]
`runtests` are now part of the deb build process.

Simplified the packaging, this is now a multi-binary package, although not yet useful as i'm still figuring out some stuff.

Had to abort the build as it was going in a loop.

**Comment by zultron** [comment]
> `runtests` are now part of the deb build process.

That's been on my wish-list for years now.  Nice!

**Comment by kinsamanka** [comment]
This is almost done. 

Next step is to convert  **machinekit-cnc** and then fix the armhf* builds.

**Comment by kinsamanka** [comment]
armhf builds fine, not yet tested on a real hw though.

@zultron ,can you please add `cmake` and `patchelf` to the `mk-cross-builder`? 😉

**Comment by MicroTransactionsMatterToo** [comment]
Where are we up to regarding actually implementing CMake? It seems like it's implemented for the most part so far, and we're just waiting for something?

**Comment by kinsamanka** [comment]
machinekit-cnc needs to be converted too.

**Comment by kdunn926** [comment]
@kinsamanka - I'd be willing to poke around on that repo and see if I can make some headway. Is there a compilation doc/readme or is it the common `configure / make` process?

**Comment by MicroTransactionsMatterToo** [comment]
@kdunn926 At the moment the build process is a bit convoluted. I've found the `build-docker` script to be best, since it won't build properly on a non-debian system. The `configure` script is located in `/debian`, and pulls from a bunch of files to setup the makefile. Subdirectories contain `Submakefile`'s, for compiling each part of the whole codebase. I'd be willing to fiddle around as well, but I'm not an expert with CMake. The main issue as far as I can tell is migrating all the numerous Automake config files and individual Submakefiles into CMake.

**Comment by kdunn926** [comment]
@MicroTransactionsMatterToo - After spending a long day on this, I see the convolution you mentioned. 😄 

Thanks for the pointers. I'm not a cmake expert by any stretch of the imagination either but it looks like I was able to wrangle a bunch of this into shape on a matching branch [here](https://github.com/kdunn926/machinekit-cnc/tree/cmake_test). There's a couple small changes needed to @kinsamanka 's branch to make sure certain header files are available, and this work also assumes a `make install` was done for `machinekit-hal` first, to land the dependent headers.  There's probably cleaner ways to pull this off but I figure this should be a good start.

It's not entirely clear to me how to test things short of just compiling and invoking the binaries manually and seeing what happens. Suggestions are welcome.

**Comment by cerna** [comment]
Super-seeded by #349.

**Pull request closed without merging**
