### PR TITLE
WHB04B-6 pendant update readme and missing rules file

### PR DESCRIPTION
**Pull request by alkabal**
Hi

If you are agree i have do a little correction for this Mpg device.

br

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by luminize** [comment]
Add to whitelist

**Comment by ArcEye** [comment]
The udev rules file needs to be specifically installed, I'll look at it later.

**Comment by ArcEye** [comment]
@alkabal 
If you edit 
https://github.com/machinekit/machinekit-hal/blob/master/debian/machinekit-hal-posix.install.in
https://github.com/machinekit/machinekit-hal/blob/master/debian/machinekit-hal-rt-preempt.install.in
https://github.com/machinekit/machinekit-hal/blob/master/debian/machinekit-hal-xenomai.install.in
and replace the last line of
`usr/share/linuxcnc/udev/90-xhc.rules`
with
`usr/share/linuxcnc/udev/*.rules`
then push the commit to your github branch (which appears to be master?)
this should pass test build.

**Comment by alkabal** [comment]
Hi

Sorry for the missing parts and many thanks for pointing to solution.

Have a nice day

**Comment by ArcEye** [comment]
Sorry did not get a notification on this one - just found it.
That seems to have solved it, I will merge.

I will probably backport this to machinekit too, as it maintains an existing element of the code.

**Comment by alkabal** [comment]
I can do the mod for machinekit if you want

**Pull request merged**
