### PR TITLE
DO NOT MERGE - CMake alternative for issue #200

### PR DESCRIPTION
**Pull request by kinsamanka**
This is only to check if it can co-exist and pass the current build system.

To build using cmake:
```
  mkdir build
  cd build
  cmake ../<src dir>
  make
  sudo make setuid
  . bin/set_env
```

There is no _**RIP**_ build. `sudo make install` will install the files to the _/usr_ directory (binaries not yet functional).

Running cmake with `-DWITH_DOCUMENTATION=on` will build the manuals.

No packaging yet.

(fix for #200)

### CODE REVIEW

**Comment by zultron** [comment]
OMG. This is exciting.

With CMake, there should be no need for a separate RIP build, and binaries should run directly out of the `build/` directory after `make`, and following that, out of `/usr/` after `make install`.  Do you mean that isn't working quite yet?

**Comment by kinsamanka** [comment]
I still need to cleanup the RPATH hack and finish converting some Submakefiles.

I've only converted the minimum that is needed to run the tests. Currently it passes all except for the two that depends on the old build system.

Also, only x86 is tested, the other architectures needs to be checked. But it's not a big issue as this cmake system can co-exist with the old, the other architectures can be slowly converted.

**Comment by cerna** [comment]
@kinsamanka 
I presume that the commands published at the top should be functional, right?

I am having problem with the locating script. It is complaining that it cannot find the `YAPPS2` package even though it is installed on my system (amd64, Debian 10).
```
/usr/lib/python2.7/dist-packages
CMake Error at cmake/Dependencies.cmake:118 (message):
  yapps not found: install yapps2 package
Call Stack (most recent call first):
  cmake/Options.cmake:40 (include)
  CMakeLists.txt:34 (include)


-- Configuring incomplete, errors occurred!
See also "/home/mars/Documents/Programming/temp/kinsamanka/build/CMakeFiles/CMakeOutput.log".
See also "/home/mars/Documents/Programming/temp/kinsamanka/build/CMakeFiles/CMakeError.log".
```
The logs are here: https://gist.github.com/cerna/8b5b24fbf6f699106657258c0c9542d0

**Comment by kinsamanka** [comment]
Please let me know what issues that you will encounter. I'm currently using Devuan Ascii (Debian Stretch equivalent) for the development.

**Comment by cerna** [comment]
@kinsamanka 
Thank you, that recent commit helped pass the `cmake` stage.

When running the `make` stage, there is an error:
```
mars@mars:~/Documents/Programming/temp/kinsamanka/build$ make
[  0%] Generating mk_rip.c
Scanning dependencies of target mk_rip.rt-preempt
[  0%] Building C object CMakeFiles/mk_rip.rt-preempt.dir/mk_rip.c.o
[  0%] Linking C shared library lib/machinekit/rt-preempt/mk_rip
[  0%] Built target mk_rip.rt-preempt
Scanning dependencies of target mk_rip
[  0%] Building C object CMakeFiles/mk_rip.dir/mk_rip.c.o
[  0%] Linking C shared library lib/machinekit/mk_rip
[  0%] Built target mk_rip
Scanning dependencies of target mk_rip.posix
[  0%] Building C object CMakeFiles/mk_rip.posix.dir/mk_rip.c.o
[  0%] Linking C shared library lib/machinekit/posix/mk_rip
[  1%] Built target mk_rip.posix
Scanning dependencies of target add_missing
[  1%] Generating ../bin/mank
[  1%] Generating ../include/config_module.h
[  1%] Generating ../include/hal.h
[  1%] Generating ../include/hal_accessor.h
[  1%] Generating ../include/hal_accessor_macros.h
[  1%] Generating ../include/hal_group.h
[  1%] Generating ../include/hal_internal.h
[  1%] Generating ../include/hal_list.h
[  1%] Generating ../include/hal_logging.h
[  1%] Generating ../include/hal_object.h
[  1%] Generating ../include/hal_object_selectors.h
[  1%] Generating ../include/hal_parport.h
[  1%] Generating ../include/hal_priv.h
[  1%] Generating ../include/hal_rcomp.h
[  1%] Generating ../include/hal_ring.h
[  1%] Generating ../include/hal_types.h
[  1%] Generating ../include/halcmd_rtapiapp.h
[  1%] Generating ../include/inifile.h
[  1%] Generating ../include/inifile.hh
[  1%] Generating ../include/multiframe.h
[  1%] Generating ../include/multiframe_flag.h
[  1%] Generating ../include/ring.h
[  2%] Generating ../include/rtapi.h
[  2%] Generating ../include/rtapi_app.h
[  2%] Generating ../include/rtapi_atomics.h
[  2%] Generating ../include/rtapi_bitops.h
[  2%] Generating ../include/rtapi_byteorder.h
[  2%] Generating ../include/rtapi_common.h
[  2%] Generating ../include/rtapi_ctype.h
[  2%] Generating ../include/rtapi_errno.h
[  2%] Generating ../include/rtapi_exception.h
[  2%] Generating ../include/rtapi_export.h
[  2%] Generating ../include/rtapi_global.h
[  2%] Generating ../include/rtapi_heap.h
[  2%] Generating ../include/rtapi_heap_private.h
[  2%] Generating ../include/rtapi_hexdump.h
[  2%] Generating ../include/rtapi_int.h
[  2%] Generating ../include/rtapi_io.h
[  2%] Generating ../include/rtapi_math.h
[  2%] Generating ../include/rtapi_math64.h
[  2%] Generating ../include/rtapi_pci.h
[  2%] Generating ../include/rtapi_shmkeys.h
[  2%] Generating ../include/rtapi_string.h
[  2%] Generating ../include/shmdrv.h
[  2%] Generating ../include/rt-preempt.h
[  2%] Generating ../include/rtapi_compat.h
[  2%] Generating ../include/triple-buffer.h
[  2%] Generating ../include/xenomai.h
[  2%] Generating ../include/pb-linuxcnc.h
[  3%] Generating ../include/syslog_async.h
[  3%] Generating ../include/czmq-watch.h
[  3%] Generating ../include/inihelp.hh
[  3%] Generating ../include/json2pb.hh
[  3%] Generating ../include/bin2ascii.hh
[  3%] Generating ../include/ll-zeroconf.hh
[  3%] Generating ../include/mk-zeroconf-types.h
[  3%] Generating ../include/mk-backtrace.h
[  3%] Generating ../include/mk-service.hh
[  3%] Generating ../include/mk-zeroconf.hh
[  3%] Generating ../include/pbutil.hh
[  3%] Generating ../include/setup_signals.h
[  3%] Generating ../include/container.h
[  3%] Generating ../include/halpb.hh
[  3%] Generating ../include/protobuf/pb.h
[  3%] Generating ../include/protobuf/pb_decode.h
[  3%] Generating ../include/protobuf/pb_encode.h
[  3%] Generating ../include/mesa/bitfile.h
[  3%] Generating ../include/mesa/hm2_pci.h
[  3%] Generating ../include/mesa/hostmot2.h
[  3%] Generating ../include/mesa/hm2_7i43.h
[  3%] Generating ../include/mesa/hm2_soc_ol.h
[  3%] Generating ../include/mesa/lbp16.h
[  3%] Generating ../include/mesa/hm2_7i90.h
[  3%] Generating ../include/mesa/hm2_test.h
[  3%] Generating ../include/mesa/sserial.h
[  3%] Generating ../include/mesa/hm2_eth.h
[  3%] Generating ../include/mesa/hostmot2-lowlevel.h
[  4%] Generating ../include/userpci/device.h
[  4%] Generating ../include/userpci/firmware.h
[  4%] Generating ../include/userpci/gfp.h
[  4%] Generating ../include/userpci/list.h
[  4%] Generating ../include/userpci/module.h
[  4%] Generating ../include/userpci/slab.h
[  4%] Generating ../include/userpci/string.h
[  4%] Built target add_missing
Scanning dependencies of target pb2json
[  4%] Creating /home/mars/Documents/Programming/temp/kinsamanka/build/lib/python/pb2json.py
[  4%] Built target pb2json
Scanning dependencies of target configserver
[  4%] Creating /home/mars/Documents/Programming/temp/kinsamanka/build/bin/configserver
[  4%] Built target configserver
Scanning dependencies of target mklauncher
[  4%] Creating /home/mars/Documents/Programming/temp/kinsamanka/build/bin/mklauncher
[  4%] Built target mklauncher
Scanning dependencies of target mkwrapper
[  4%] Creating /home/mars/Documents/Programming/temp/kinsamanka/build/bin/mkwrapper
[  4%] Built target mkwrapper
Scanning dependencies of target videoserver
[  4%] Creating /home/mars/Documents/Programming/temp/kinsamanka/build/bin/videoserver
[  4%] Built target videoserver
Scanning dependencies of target nanopb
[  4%] Building C object src/machinetalk/nanopb/CMakeFiles/nanopb.dir/pb_common.c.o
[  4%] Building C object src/machinetalk/nanopb/CMakeFiles/nanopb.dir/pb_encode.c.o
[  4%] Building C object src/machinetalk/nanopb/CMakeFiles/nanopb.dir/pb_decode.c.o
[  4%] Built target nanopb
Scanning dependencies of target nanopb_generator.py
[  4%] Generating ../../../lib/python/protobuf/nanopb_generator.py
[  4%] Built target nanopb_generator.py
Scanning dependencies of target protoc-gen-nanopb
[  4%] Generating ../../../lib/python/protobuf/protoc-gen-nanopb
[  4%] Built target protoc-gen-nanopb
Scanning dependencies of target nanopb.npb.h
[  4%] Generate python files from src/machinetalk/protobuf/value.proto
[  4%] Generate python files from src/machinetalk/protobuf/canon.proto
[  4%] Generate python files from src/machinetalk/protobuf/config.proto
[  4%] Generate python files from src/machinetalk/protobuf/emcclass.proto
[  4%] Generate python files from src/machinetalk/protobuf/firmware.proto
[  4%] Generate python files from src/machinetalk/protobuf/jplan.proto
[  4%] Generate python files from src/machinetalk/protobuf/log.proto
[  4%] Generate python files from src/machinetalk/protobuf/message.proto
[  4%] Generate python files from src/machinetalk/protobuf/motcmds.proto
[  6%] Generate python files from src/machinetalk/protobuf/nanopb.proto
[  6%] Generate python files from src/machinetalk/protobuf/object.proto
[  6%] Generate python files from src/machinetalk/protobuf/preview.proto
[  6%] Generate python files from src/machinetalk/protobuf/ros.proto
[  6%] Generate python files from src/machinetalk/protobuf/rtapi_message.proto
[  6%] Generate python files from src/machinetalk/protobuf/rtapicommand.proto
[  6%] Generate python files from src/machinetalk/protobuf/sample.proto
[  6%] Generate python files from src/machinetalk/protobuf/status.proto
[  6%] Generate python files from src/machinetalk/protobuf/task.proto
[  6%] Generate python files from src/machinetalk/protobuf/test.proto
[  6%] Generate python files from src/machinetalk/protobuf/types.proto
[  6%] Generate npb cpp files from src/machinetalk/protobuf/nanopb.proto
[  6%] Built target nanopb.npb.h
[  6%] Generate npb cpp files from src/machinetalk/protobuf/canon.proto
[  6%] Generate npb cpp files from src/machinetalk/protobuf/config.proto
[  6%] Generate npb cpp files from src/machinetalk/protobuf/emcclass.proto
[  6%] Generate npb cpp files from src/machinetalk/protobuf/firmware.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/jplan.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/log.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/message.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/motcmds.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/object.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/preview.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/ros.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/rtapi_message.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/rtapicommand.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/sample.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/status.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/task.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/test.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/types.proto
[  7%] Generate npb cpp files from src/machinetalk/protobuf/value.proto
Scanning dependencies of target npb-obj
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/canon.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/config.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/emcclass.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/firmware.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/jplan.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/log.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/message.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/motcmds.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/object.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/preview.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/ros.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/rtapi_message.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/rtapicommand.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/sample.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/status.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/task.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/test.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/types.npb.c.o
[  7%] Building C object src/machinetalk/proto/CMakeFiles/npb-obj.dir/protobuf/value.npb.c.o
[  8%] Built target npb-obj
Scanning dependencies of target machinetalk-npb
[  9%] Building C object src/machinetalk/proto/CMakeFiles/machinetalk-npb.dir/protobuf/nanopb.npb.c.o
[  9%] Linking C shared library ../../../lib/libmachinetalk-npb.so
[  9%] Built target machinetalk-npb
[  9%] Generate cpp files from src/machinetalk/protobuf/value.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/canon.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/config.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/emcclass.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/firmware.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/jplan.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/log.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/message.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/motcmds.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/nanopb.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/object.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/preview.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/ros.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/rtapi_message.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/rtapicommand.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/sample.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/status.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/task.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/test.proto
[  9%] Generate cpp files from src/machinetalk/protobuf/types.proto
Scanning dependencies of target machinetalk-pb2++
[  9%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/canon.pb.cc.o
[  9%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/config.pb.cc.o
[  9%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/emcclass.pb.cc.o
[  9%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/firmware.pb.cc.o
[  9%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/jplan.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/log.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/message.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/motcmds.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/nanopb.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/object.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/preview.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/ros.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/rtapi_message.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/rtapicommand.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/sample.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/status.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/task.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/test.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/types.pb.cc.o
[ 10%] Building CXX object src/machinetalk/proto/CMakeFiles/machinetalk-pb2++.dir/protobuf/value.pb.cc.o
[ 10%] Linking CXX shared library ../../../lib/libmachinetalk-pb2++.so
Warning: Unused direct dependencies:
	/lib/x86_64-linux-gnu/libm.so.6
[ 10%] Built target machinetalk-pb2++
Scanning dependencies of target syslog_async
[ 10%] Building C object src/machinetalk/lib/CMakeFiles/syslog_async.dir/syslog_async.c.o
[ 10%] Built target syslog_async
Scanning dependencies of target mtalk
[ 10%] Building C object src/machinetalk/lib/CMakeFiles/mtalk.dir/czmq-watch.c.o
cc: error: missing path after ‘-isystem’
cc: fatal error: no input files
compilation terminated.
/bin/sh: 1: /usr/include/mit-krb5: Permission denied
/bin/sh: 1: -I/usr/include/pgm-5.2: not found
/bin/sh: 1: -I/usr/include/uuid: not found
make[2]: *** [src/machinetalk/lib/CMakeFiles/mtalk.dir/build.make:63: src/machinetalk/lib/CMakeFiles/mtalk.dir/czmq-watch.c.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:2446: src/machinetalk/lib/CMakeFiles/mtalk.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by kinsamanka** [comment]
This is a `pkg-config` issue.
under stretch:
```
pkg-config --cflags libczmq

```
under buster:
```
pkg-config --cflags libczmq
-isystem /usr/include/mit-krb5 -I/usr/include/pgm-5.2 -I/usr/include/uuid
```

**Comment by cerna** [comment]
Thanks, that seems like it solved it. Now, on my machine it builds. Will have to try to install it on sacrificial machine tomorrow.

It's kinda sad that the distro versions are osmosing into build recipes even in high on abstraction build systems.

**Comment by kinsamanka** [comment]
must close 🤦‍♂ :face

**Pull request closed without merging**
