### PR TITLE
Modify module loading to always load flavor related function via specific module

### PR DESCRIPTION
**Pull request by cerna**
This pull request implements the following functionality:

- Make sure that the flavor related function are always `dlsym`ed from specific module (shared library), the `RTAPIMOD` to be exact
- Repair segmentation fault in `icomp` HAL managed module which this change uncovered

### CODE REVIEW

**Comment by cerna** [comment]
The reason why this failed on Drone Cloud is that the #351 includes fixes for `armhf` based build - which this PR obviously does not have.

It will need to be rebased after #351 is merged.

**Comment by cerna** [comment]
Should be fine to merge now.

**Comment by the-snowwhite** [comment]
I'll merge as soon as the checks have passed

**Comment by cerna** [comment]
> I'll merge as soon as the checks have passed

Yes, sorry, it looks like it is the favourite error on `build/machinekit-hal/tests/threads.0` - which is caused by inability to set the right capability in Drone Cloud. I restarted it and will monitor.

**Comment by the-snowwhite** [comment]
ok

**Comment by the-snowwhite** [comment]
:-) sometime all thats needed is some kind attention...

**Pull request merged**
