### PR TITLE
Put dependencies in correct control files

### PR DESCRIPTION
**Pull request by ArcEye**
Create build specific postinst files in the configure process

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
Don't merge straight away please
Need to check the postinst script is correct, keeps getting over ridden by defaults instead of appended to them

**Comment by ArcEye** [comment]
That appears to have done it - OK to merge
I will test the packages again tomorrow

**Comment by ArcEye** [comment]
Bump!

**Comment by cdsteinkuehler** [comment]
Sorry, been away from the computer.  Merged.

**Pull request merged**
