### PR TITLE
GitHub actions multibranch repair

### PR DESCRIPTION
**Pull request by cerna**
This pull request is repair for issue reported by @zultron in machinekit/machinekit-hal#293 and further described in [this message](https://github.com/machinekit/machinekit-hal/issues/268#issuecomment-674449395).

This pull request removes the GraphQL API querying as one cannot get the Docker image manifest through it and querying the Docker API one can get the same information (which makes querying the GitHub GraphQL API moot task).

Basis for this pull request is to allow multi-branch work on Machinekit-HAL repository.

### CODE REVIEW

**Comment by cerna** [comment]
Somehow @zultron's commits were included, I will repair it tomorrow.

**Comment by cerna** [comment]
And I didn't really test it as a pull request, damn! I will all solve it tomorrow.

**Comment by cerna** [comment]
I probably went at it wrong - I don't need the information about branch in Docker images. Can anybody think of situation when docker image built from certain Git SHA (this build is valid, tests run green), would not be usable, when the same Git SHA is in current git tree and between given Git SHA and HEAD no files pertaining build system were changed?

**Comment by zultron** [comment]
> Can anybody think of situation when docker image built from certain Git SHA (this build is valid, tests run green), would not be usable, when the same Git SHA is in current git tree and between given Git SHA and HEAD no files pertaining build system were changed?

This is the same assumption I made in another project, and it has never been proven wrong.

Instead of doing git-fu, I did this to generate a short hash of the Docker input files.  In this use case, it could be added as an image label and queried on the registry.  If the registry image label's matches the local files' computed hash, pull the image, else build a new one.
```
        export LC_ALL=C.UTF-8 # Be sure sorting is consistent
        cd $DOCKER_SCRIPTS_DIR
        find . -type f -print0 |
            sort -z |
            xargs -0 sha1sum |
            sha1sum |
            cut -c -8
```

**Comment by cerna** [comment]
Thanks, the _git-fu_ is already done, so I kept it as is. I will change it to your example if it will turn out problematic :+1:

I removed the checking of branch name in the CI workflow. Stupidly, I didn't realize that in detached HEAD state (this week is not a good week), which are all pull requests and maybe other events, the branch name is **HEAD**. Given that the logic is implementable by checking git SHA only and there is no reason to be rebuilding just on branch name when the aforementioned input conditions are true, I think it will be better that way.

I kept the branch label in the build process, because it is much easier to just look at the manifest and see from which branch it was built (both in Github Actions CI and on local developer's machine) than tracking down the git SHA. (But it is frivolous information.)

I think this is good to merge.

**Pull request merged**
