### PR TITLE
Python3: fix configparser letter case in 4 files

### PR DESCRIPTION
**Pull request by the-snowwhite**
ConfigParser is renamed to configparser in python3

Signed-off-by: Holotronic <producer@holotronic.dk>

### CODE REVIEW

**Comment by the-snowwhite** [comment]
@cerna 
Whats this error message:

> 

Test RIP version on ubuntu 20.04 arm64: Error response from daemon: toomanyrequests: 
You have reached your pull rate limit. 
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Test RIP version on ubuntu 20.04 arm64 – Prepare Docker Drone volume: Error

about ?

Edit: Odd now error is gone

**Comment by cerna** [comment]
@the-snowwhite,
the whole Drone Cloud is running on few servers and all jobs (basically containers in Docker) are all sharing it. So you are depending at the actual current load when your job starts. (_This can be sort of _abused_ for the FPGA build._) 

So I would say that at the moment the load on the server is too high.

**Comment by the-snowwhite** [comment]
@cerna  ok so it has nothing to do with [this](https://github.com/machinekit/machinekit-hal/issues/337) ?

**Comment by cerna** [comment]
Now the build on Drone Cloud went fine on merge to master. It really looks like time problem and load problem. In either case it is too bad for Machinekit.

Drone [published](https://discourse.drone.io/t/docker-hub-rate-limits-and-drone-cloud-exemption/8293/14) discourse about this issue.

**Pull request merged**
