### PR TITLE
2020 05 09 rebranding pr

### PR DESCRIPTION
**Pull request by zultron**
Following #279 and #280, this is the third of four PRs to support building LCNC-EMC on MK-HAL.

This PR renames everything EMC2 to HAL, and everything LinuxCNC to either Machinekit or HAL.  Really, only the bottom commit "Mass replace `EMC2` with `HAL`" actually helps the LCNC-EMC on MK-HAL effort, since it resolves conflicts in the configuration variables, most notably `$EMC2_HOME`.

The other two commits are the result of a moment's inspiration followed by hours of tedium.

### CODE REVIEW

**Comment by zultron** [comment]
As always, let me know if this is too controversial.

**Comment by zultron** [comment]
Hold off on this one; I didn't split it off just where I wanted to

**Comment by cerna** [comment]
Are we good to merge?

**Comment by zultron** [comment]
OK, looking good!

**Comment by cerna** [comment]
And done. Let me say, I was chagrined by the number of `linuxcnc`s or `EMC2`s in place where should be `Machinekit`s or `Machinekit-HAL`s, but was too lazy to actually change all.

So, thank you.

**Comment by cerna** [comment]
Some manual testing trying to install this:
```
Do you want to continue? [Y/n] y
Get:1 https://dl.cloudsmith.io/public/machinekit/machinekit-hal/deb/debian buster/main amd64 machinekit-hal-dev amd64 0.3.1588961152.git10f5a51-1~buster [245 kB]
Get:2 https://dl.cloudsmith.io/public/machinekit/machinekit-hal/deb/debian buster/main amd64 machinekit-hal-dbgsym amd64 0.3.1588961152.git10f5a51-1~buster [12.2 MB]
Get:3 https://dl.cloudsmith.io/public/machinekit/machinekit-hal/deb/debian buster/main amd64 machinekit-hal amd64 0.3.1588961152.git10f5a51-1~buster [1,634 kB]
Get:4 https://dl.cloudsmith.io/public/machinekit/machinekit-hal/deb/debian buster/main amd64 machinekit-hal-rt-preempt amd64 0.3.1588961152.git10f5a51-1~buster [2,942 B]                          
Fetched 14.1 MB in 6s (2,243 kB/s)                                                                                                                                                                 
Reading changelogs... Done
(Reading database ... 981486 files and directories currently installed.)
Preparing to unpack .../machinekit-hal-dev_0.3.1588961152.git10f5a51-1~buster_amd64.deb ...
Unpacking machinekit-hal-dev (0.3.1588961152.git10f5a51-1~buster) over (0.3.1588958026.git18ceeea-1~buster) ...
Preparing to unpack .../machinekit-hal-dbgsym_0.3.1588961152.git10f5a51-1~buster_amd64.deb ...
Unpacking machinekit-hal-dbgsym (0.3.1588961152.git10f5a51-1~buster) over (0.3.1588958026.git18ceeea-1~buster) ...
Preparing to unpack .../machinekit-hal_0.3.1588961152.git10f5a51-1~buster_amd64.deb ...
Unpacking machinekit-hal (0.3.1588961152.git10f5a51-1~buster) over (0.3.1588958026.git18ceeea-1~buster) ...
dpkg: error processing archive /var/cache/apt/archives/machinekit-hal_0.3.1588961152.git10f5a51-1~buster_amd64.deb (--unpack):
 trying to overwrite '/usr/share/machinekit/Makefile.inc', which is also in package machinekit-hal-dev 0.3.1588961152.git10f5a51-1~buster
Valid MKUUID in mkuuid f782351a-006e-49de-8c1b-43be69f7aa50 - using that
Valid value in ini file f782351a-006e-49de-8c1b-43be69f7aa50 - leaving
Preparing to unpack .../machinekit-hal-rt-preempt_0.3.1588961152.git10f5a51-1~buster_amd64.deb ...
Unpacking machinekit-hal-rt-preempt (0.3.1588961152.git10f5a51-1~buster) over (0.3.1588958026.git18ceeea-1~buster) ...
Errors were encountered while processing:
 /var/cache/apt/archives/machinekit-hal_0.3.1588961152.git10f5a51-1~buster_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by cerna** [comment]
Yeah, it is a problem, @zultron, `machinekit-hal` and `machinekit-hal-dev` become un-co-installable again.

(Purging from system and cannot be installed again. This is specific to this pull request. [Last one could be upgraded normally].)

Problem similar to #271.

**Pull request merged**
