### PR TITLE
Python 3 port:  Supersedes #299

### PR DESCRIPTION
**Pull request by zultron**
This is a rebase of #299, including fixes from rene-dev#1.

### CODE REVIEW

**Comment by zultron** [comment]
Submitted this in part to investigate the Drone failures @cerna pointed out.

This is marked as a draft for now.

**Comment by cerna** [comment]
I wouldn't put too much hope into the Drone testing, I may be that I implemented it too naively.

**Comment by zultron** [comment]
Expected test failure in `tests/halmodule.0`, Debian 9+10 armhf:

https://cloud.drone.io/machinekit/machinekit-hal/31/3/3
https://cloud.drone.io/machinekit/machinekit-hal/31/6/3

Unexpected test failure in `tests/mux`, Debian 10 amd64 (@cerna have you seen this before?):

https://cloud.drone.io/machinekit/machinekit-hal/31/1/3

**Comment by cerna** [comment]
@zultron,
yah, the tests have been failing non-deterministically in Drone Cloud. I have a feeling that it is caused by the `su ...` switching I have done to avoid caching the images. (In Drone, you have to upload the build image somewhere before you can use it in next step. No way around it.)

I will have to redo it so it implements the same caching as the Github Actions. (Well, I played it let'n'loose and it didn't pan out.)

---

I reran it and it passed.

**Comment by zultron** [comment]
Hmm, a `threads.0` failure and an `hm2_idrom` failure.
https://travis-ci.com/github/machinekit/machinekit-hal/jobs/378624693 threads.0
https://travis-ci.com/github/machinekit/machinekit-hal/jobs/378624695 threads.0
https://cloud.drone.io/machinekit/machinekit-hal/37/1/3 hm2-idrom

**Comment by cerna** [comment]
I cannot find file `sys/io.h` with an error `/usr/bin/ls: cannot access '/usr/include/arm-linux-gnueabihf/sys/io.h': No such file or directory` on _QEMU_ run _Ubuntu:focal_, **armhf**.

But I can find it on _QEMU_ run _Ubuntu:bionic_, **armhf**. (Same sequence of commands.)

Did they remove the _sys/io.h_ header from _armhf_ completely (or did they remove it to separate package)?

---

It is missing in the files list:

[libc6-dev, amd64](https://packages.ubuntu.com/focal/amd64/libc6-dev/filelist) (the `sys/io.h` present)
[libc6-dev, armhf](https://packages.ubuntu.com/focal/armhf/libc6-dev/filelist) (the `sys/io.h` **not** present)

But not from **musl**

[musl-dev, amd64](https://packages.ubuntu.com/focal/amd64/musl-dev/filelist) (the `sys/io.h` present)
[musl-dev, armhf](https://packages.ubuntu.com/focal/armhf/musl-dev/filelist) (the `sys/io.h` **present**)
but then:
[musl-dev, arm64](https://packages.ubuntu.com/focal/arm64/musl-dev/filelist) (the `sys/io.h` **also present**)

So the musl C library is probably done differently (in this aspect).

---

Probably better solution would be to not decide this based on architecture, but test the existence of **sys/io.h** in the configure script. Lesson learned.

**Comment by zultron** [comment]
> Did they remove the _sys/io.h_ header from _armhf_ completely

Well, I'm still working on building a Ubuntu Focal `armhf` Docker image on my Rpi4.  I'm hitting this error:
```
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal InRelease' is not signed.
```
...which is apparently a misleading error that masks the [real underlying problem][1] where `utime(2)` is blocked by `libseccomp` in unprivileged containers (such as those that `docker build`s run in).

I'm trying a two-prong approach, hacking the upstream `ubuntu:focal` container and installing kerner v5.x on the Rpi4.

I'm not even 100% sure that's the problem yet.  I'm a bit surprised that the Drone CI ARM-arch runners even have 5.x kernels, since most of the (several) ARM boards I have come with 4.x kernels by default, and many don't even have the option to upgrade.

[1]: https://github.com/moby/moby/issues/40734

Edit:  I misunderstood and this is very easy to resolve on the *host*, not inside the container, and without upgrading the kernel:
```
# https://packages.debian.org/sid/armhf/libseccomp2/download
wget http://http.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.3-1+b1_armhf.deb
sudo dpkg -i libseccomp2_2.4.3-1+b1_armhf.deb
```

**Comment by cerna** [comment]
@zultron,
>[...] I'm a bit surprised that the Drone CI ARM-arch runners even have 5.x kernels, since most of the (several) ARM boards I have come with 4.x kernels by default, and many don't even have the option to upgrade.

Last time I checked, it was using **4.x** kernel version:
```
Linux 57041ac8f2e6 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:16 UTC 2018 armv8l GNU/Linux
```

They are using servers from [PACKET](https://www.packet.com/), specifically _"Cavium ThunderX processor with 96 physical cores and 128 GB of RAM"_.

But be aware that so far you have to add the builders rules by hand to `.drone/drone.yaml` - the automatic generation will have to be done in **pre-commit** hook on the developer's machine. And that is something I did not implement yet. (So now the ubuntu is not tested on Drone Cloud or Travis CI. I will add it to zultron/machinekit-hal#2.)

>Well, I'm still working on building a Ubuntu Focal armhf Docker image on my Rpi4.

Have you tried the _buildx_ and just running the container on Rasberry Pi?

**Comment by cerna** [comment]
And on Drone it is immediatelly the same problem:
```
+ apt-get update
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [111 kB]
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  At least one invalid signature was encountered.
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [98.3 kB]
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  At least one invalid signature was encountered.
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [107 kB]
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-security InRelease' is not signed.
```
Can be seen [here](https://cloud.drone.io/cerna/machinekit-hal/199/3/3).

**Comment by cerna** [comment]
@zultron,
I presume you haven't tried [this](https://github.com/zultron/machinekit-hal/commit/58e2f1c68dd55288914118c70d5332f72d8d484d#diff-f7f51fd7d512e8df9d8f7e04a03d1339R126) code on `arm64` hardware with native build, right? Because it is little bit trashing the `/etc/apt/sources.list` with [amd64](https://travis-ci.com/github/cerna/machinekit-hal/jobs/378836853#L1399) sources.

(It's no matter, I have working solution which can survive even cross compilation from _arm64_. So I would merge this without the Drone and Travis testing support and I will then open new pull request which will solve this.)

**Comment by zultron** [comment]
> And on Drone it is immediatelly the same problem:

Ah, OK.  And I'm not seeing how to fix it in the Drone config, since it looks like everything runs inside a container and there's no access to the host OS.

> Have you tried the _buildx_ and just running the container on Rasberry Pi?

No, since it was solved per my edits at the bottom of https://github.com/machinekit/machinekit-hal/pull/303#issuecomment-682513545.



> I presume you haven't tried [this](https://github.com/zultron/machinekit-hal/commit/58e2f1c68dd55288914118c70d5332f72d8d484d#diff-f7f51fd7d512e8df9d8f7e04a03d1339R126) code on `arm64` hardware with native build, right? Because it is little bit trashing the `/etc/apt/sources.list` with [amd64](https://travis-ci.com/github/cerna/machinekit-hal/jobs/378836853#L1399) sources.

Right, we talked about that before, which led to your issue #302, I guess.  It would be easy enough to fix that same `RUN` statement to do the right thing, unless you've already done something else.

**Comment by cerna** [comment]
>Ah, OK. And I'm not seeing how to fix it in the Drone config, since it looks like everything runs inside a container and there's no access to the host OS.

No, you cannot. Drone is actually pretty limited in what you can do and what it can do. The Docker idea is theoretically interesting and novel idea, but in practical terms it leaves much to be desired.

I will try to open up discussion on the Drone Discourse. I don't think there is anything else to do.

>Right, we talked about that before, which led to your issue #302, I guess.

Yeah, to open up the discussion a bit. But nobody has any opinion, so I am going to leave at Debian and Ubuntu

>It would be easy enough to fix that same RUN statement to do the right thing, unless you've already done something else.

Leave it, I have something. So, lets merge this and I will tickle the build scripts later (soon).

**Comment by cerna** [comment]
Fuck, did the **.** (dot) in package name (`machinekit-hal-ubuntu-arm64-20.04-ebe1344a0bf66a1793e1fe52d0c11a55475449cb-1598643033`) cause, that it was not uploaded to the Cloudsmith repository?

It looks for regex: `^.*/machinekit-hal-([a-z]{1,})-([a-z0-9]{1,})-([0-9]{1,})-${{ github.sha }}-${{ needs.prepareState.outputs.Timestamp }}/.{1,}\.deb$`. ~~And it will probably cause problems (the dot, I mean) with Debian package versioning.~~ (The dot is actually in folder name, nothing to do with the package.)

And the **.deb** and **.ddeb** distinction too. The regex has to be changed.

**Pull request merged**
