### PR TITLE
rtapi/rtapi_pci.c:  Fix PCI resource file parsing

### PR DESCRIPTION
**Pull request by zultron**
Fixes a problem introduced in commit e207745f.  Thanks to Dennis for
reporting the problem and locating the problematic commit on the [ML][1].

[1]:  https://groups.google.com/d/msg/machinekit/KQFyNEsnblE/gX_-g36tCQAJ

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by zultron** [comment]
On the ML, I requested Dennis give this a try.  Consider holding off a few days on merging this until we get or don't get his results.

**Comment by luminize** [comment]
Add to whitelist

**Comment by ArcEye** [comment]
@zultron 
Dennis probably won't be able to test this, his problem and the temp fix were in the machinekit repo.
I just copied over to here to make sure this worked too in the interim.

Can you PR this to machinekit too please.
Just delete the text telling you not to when you open it!

**Comment by zultron** [comment]
Thanks, @ArcEye.  Copied to machinekit/machinekit#1478 .

**Comment by ArcEye** [comment]
Dennis has tested packages I built from this PR and they function properly - merging

**Pull request merged**
