### PR TITLE
Update merge2

### PR DESCRIPTION
**Pull request by ArcEye**
Catch up of commits to machinekit/master which are relevant, up to 06042017.

### CODE REVIEW

**Comment by ArcEye** [comment]
@machinekoder unless you did submit a review for this PR, ignore.
I seem to have triggered something inadvertently by clicking on your avatar to see why it was displayed.

**Comment by ArcEye** [comment]
@luminize @machinekoder 
are you getting notifications of PRs from this repo?

I thought I had added everyone, but maybe not

**Comment by luminize** [comment]
@ArcEye yes I get a notification, and I see that I also got the notification of the PR #2 too. All’s working on my side.

**Comment by ArcEye** [comment]
Good, when you have a chance can you merge it, the actual changes were already reviewed when submitted to machinekit/master, just keeping this one up to date.

**Comment by luminize** [comment]
done

**Comment by ArcEye** [comment]
Thanks

**Pull request merged**
