### PR TITLE
Silence compiler warnings 1

### PR DESCRIPTION
**Pull request by ArcEye**
First batch of @zultron s commits to machinekit repo to silence compiler warnings

### CODE REVIEW

**Comment by ArcEye** [comment]
It is failing on one of the package build steps that @zultron introduced.
Works in machinekit, so probably something slightly different in the machinekit-hal debian/rules
Look at it later

**Comment by luminize** [comment]
Give a shout when ready, hand is near the merge button

**Comment by ArcEye** [comment]
@luminize 
OK that fixed it, ready to merge this one and #152

**Comment by zultron** [comment]
Thanks, guys.

**Pull request merged**
