### PR TITLE
2020 05 07 misc cleanups pr

### PR DESCRIPTION
**Pull request by zultron**
This is the first of four PRs to support building LCNC-EMC on MK-HAL.

The changes in this PR aren't all directly to support the LCNC-EMC build, but they are improvements on the MK-HAL code even if the final LCNC-EMC support PR is never merged.

General areas of improvement:
- Remove obsolete code
- Fix `runtests` to run on installed packages
- Move `comp`, `instcomp`, `runtests` to `-dev` package
- Switch to GPL-compatible `readline` library
- Build system updates
- Rename `liblinuxcncfoo.so` libraries to `libfoo.so`

### CODE REVIEW

**Comment by cerna** [comment]
@zultron,
this has no chance of passing the `.github/workflows/build-preview.yaml` as it is now and I think it outlived its usefulness.

Could you add commit and delete it?

Thanks.

**Comment by zultron** [comment]
Done, thanks.

Build passing (after a little fixup commit).

**Comment by cerna** [comment]
OK, will merge immediately after workflow turns green.

**Comment by cerna** [comment]
Updating from Cloudsmith repository I had this error:

```
Unpacking libclang-cpp11 (1:11~++20200507122935+717bef66232-1~exp1~20200507103538.754) over (1:11~++20200507120143+07b69dcf667-1~exp1~20200506220745.753) ...
Preparing to unpack .../2-libllvm11_1%3a11~++20200507122935+717bef66232-1~exp1~20200507103538.754_amd64.deb ...
Unpacking libllvm11:amd64 (1:11~++20200507122935+717bef66232-1~exp1~20200507103538.754) over (1:11~++20200507120143+07b69dcf667-1~exp1~20200506220745.753) ...
Preparing to unpack .../3-libwebkit2gtk-4.0-37_2.28.2-2~deb10u1_amd64.deb ...
Unpacking libwebkit2gtk-4.0-37:amd64 (2.28.2-2~deb10u1) over (2.26.4-1~deb10u3) ...
Preparing to unpack .../4-libjavascriptcoregtk-4.0-18_2.28.2-2~deb10u1_amd64.deb ...
Unpacking libjavascriptcoregtk-4.0-18:amd64 (2.28.2-2~deb10u1) over (2.26.4-1~deb10u3) ...
Preparing to unpack .../5-machinekit-hal-dev_0.3.1588939790.git1143428-1~buster_amd64.deb ...
Unpacking machinekit-hal-dev (0.3.1588939790.git1143428-1~buster) over (0.3.1588837556.git23e0d1d-1~buster) ...
dpkg: error processing archive /tmp/apt-dpkg-install-ZExmaC/5-machinekit-hal-dev_0.3.1588939790.git1143428-1~buster_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/comp', which is also in package machinekit-hal 0.3.1588837556.git23e0d1d-1~buster
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../6-machinekit-hal-dbgsym_0.3.1588939790.git1143428-1~buster_amd64.deb ...
Unpacking machinekit-hal-dbgsym (0.3.1588939790.git1143428-1~buster) over (0.3.1588837556.git23e0d1d-1~buster) ...
Preparing to unpack .../7-machinekit-hal_0.3.1588939790.git1143428-1~buster_amd64.deb ...
Unpacking machinekit-hal (0.3.1588939790.git1143428-1~buster) over (0.3.1588837556.git23e0d1d-1~buster) ...
Preparing to unpack .../8-machinekit-hal-rt-preempt_0.3.1588939790.git1143428-1~buster_amd64.deb ...
Unpacking machinekit-hal-rt-preempt (0.3.1588939790.git1143428-1~buster) over (0.3.1588837556.git23e0d1d-1~buster) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ZExmaC/5-machinekit-hal-dev_0.3.1588939790.git1143428-1~buster_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
resolving by `sudo apt--fix-broken install` worked.

~~Not sure about the cause.~~ Sure, the `comp` **-dev** problem. OK, nothing to see there.

**Pull request merged**
