### PR TITLE
halcmd: Do not truncate lines and continue silently

### PR DESCRIPTION
**Pull request by mbuesch**
The root cause of the issue https://github.com/machinekit/machinekit-hal/issues/217 was very hard to find, because halcmd truncates too-long lines and silently continues with the truncated content. That results in random errors in any other subsystem or even misbehaviour during runtime, which makes it very hard to debug.

The line length limit has been raised since then, but halcmd still truncates long lines.
Fix that by throwing an error, if the line length limit is exceeded.

### CODE REVIEW

**Comment by ArcEye** [comment]
I am not seeing where halcmd truncates lines and continues

https://github.com/machinekit/machinekit-hal/blob/master/src/hal/utils/halcmd_main.c#L282 should exit if the command line exceeds `CMD_BUF_LEN`
(albeit it is within strange bracketing and is _after_ the parsing loop, whereas you would think this should be the first check. )
```
char cmdline[MAX_CMD_LEN];
	cmdline[0] = '\0';
	int i, len = 0;
	for (i=1; i < argc; i++) {
	    len += strlen(argv[i]) + 1;
	    if (len < MAX_CMD_LEN) {
		strcat(cmdline, argv[i]);
		strcat(cmdline, " ");
	    }
	    else {
		fprintf(stderr, "halcmd commandline exceeds %i chars", MAX_CMD_LEN);
		exit(-1);
	    }
	}
	rtapi_print_msg(RTAPI_MSG_DBG, "--halcmd %s", cmdline);
```

Do you have an example command line that causes this issue and a debug print linuxcnc.log for it?

**Comment by mbuesch** [comment]
Sorry, my wording was imprecise.
This is about a line from the HAL file. Not about the actual halcmd executable command line.
You can test this by adding about 1000 white space preceding the actual command in the HAL file.
The actual error in the log will depend on where you put the white space.

The problem is that the fgets truncates the line after max-chars and then the next call to fgets interprets the rest of that line as the _next_ line. If that rest is some non-whitespace, it will do random things.

Try this modified core_sim.hal (only the line loadrt EMCMOT... is changed):

```
# core HAL config file for simulation

# first load all the RT modules that will be needed
# kinematics
loadrt trivkins
# trajectory planner
loadrt tp
# motion controller, get name and thread periods from ini file
loadrt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [EMCMOT]EMCMOT base_period_nsec=[EMCMOT]BASE_PERIOD servo_period_nsec=[EMCMOT]SERVO_PERIOD num_joints=[TRAJ]AXES kins=trivkins tp=tp
# load 6 differentiators (for velocity and accel signals
loadrt ddt names=ddt_x,ddt_xv,ddt_y,ddt_yv,ddt_z,ddt_zv
# load additional blocks
loadrt hypot names=vel_xy,vel_xyz

# add motion controller functions to servo thread
addf motion-command-handler servo-thread
addf motion-controller servo-thread
# link the differentiator functions into the code
addf ddt_x servo-thread
addf ddt_xv servo-thread
addf ddt_y servo-thread
addf ddt_yv servo-thread
addf ddt_z servo-thread
addf ddt_zv servo-thread
addf vel_xy servo-thread
addf vel_xyz servo-thread

# create HAL signals for position commands from motion module
# loop position commands back to motion module feedback
net Xpos axis.0.motor-pos-cmd => axis.0.motor-pos-fb ddt_x.in
net Ypos axis.1.motor-pos-cmd => axis.1.motor-pos-fb ddt_y.in
net Zpos axis.2.motor-pos-cmd => axis.2.motor-pos-fb ddt_z.in

# send the position commands thru differentiators to
# generate velocity and accel signals
net Xvel ddt_x.out => ddt_xv.in vel_xy.in0
net Xacc <= ddt_xv.out
net Yvel ddt_y.out => ddt_yv.in vel_xy.in1
net Yacc <= ddt_yv.out
net Zvel ddt_z.out => ddt_zv.in vel_xyz.in0
net Zacc <= ddt_zv.out

# Cartesian 2- and 3-axis velocities
net XYvel vel_xy.out => vel_xyz.in1
```

It will truncate before tp=tp and thus result in this error:

```
core_sim.hal:10: Unknown command 'tp=tp'
```

With my change it will throw a proper parser error.

**Comment by ArcEye** [comment]
OK, see what you mean now.

Can we just change the error message to 
`"ERROR: hal file command line too long (>=%d).\n"` so that it is obvious in the log that it comes from
parsing the hal file.

I was going to suggest that the offending line be printed, but I think that would cause Axis some problems and any other GUI that displays the errors.

**Comment by mbuesch** [comment]
What about that?
It will print the file name and approximate line number, too.

```
core_sim.hal:8: The hal file command line is too long (>=1023).
```

**Comment by mbuesch** [comment]
I added a commit to fix the line number in the error message to be exact.
Most of the change is white space, because indent was neither correct for tab=4, nor for tab=8 in that area.

**Comment by ArcEye** [comment]
>  Most of the change is white space, because indent was neither correct for tab=4, nor for tab=8 in that area.

There is a lot not to like about some of the halcmd code.  I find the insistence upon using kernel type bracketing and 80 char long lines, makes it hard to read in some places, unless you have an editor with bracket match highlighting.

>  What about that?
It will print the file name and approximate line number, too.
`core_sim.hal:8: The hal file command line is too long (>=1023).`

That would be ideal, did your last commit remove it again?

**Comment by mbuesch** [comment]
> That would be ideal, did your last commit remove it again?

No. The last commit just changed the line number to 9, because the error actually is in line 9.
Just the ordering of halcmd_set_linenumber vs. get_input has been swapped. The rest is white space changes (see git diff -w)

**Comment by ArcEye** [comment]
I am obviously missing something, been going in circles until I am doubting my sanity!

Where is the code
```
halcmd_error("%s:%d: The hal file command line is too long (>=%d).\n",
                     size - 1, filename, linenumber);
```
that would be required to produce that error message?

**Comment by mbuesch** [comment]
halcmd_error() does add the file:line information internally by use of the global parser state. My last commit fixes that global parser state (line number).

**Comment by ArcEye** [comment]
I am trying to balance too many plates at present :(

**Pull request merged**
