### PR TITLE
Add && operator between bash commands in Travis CI recipe

### PR DESCRIPTION
**Pull request by cerna**
This pull request solves the same issue as machinekit/machinekit-hal#293. (This time for Travis CI configuration.)

The [problem](https://github.com/machinekit/machinekit-hal/issues/268#issuecomment-678639791) was discovered when looking at machinekit/machinekit-hal#299.

(Probably better to merge after machinekit/machinekit-hal#298.)

### CODE REVIEW

**Comment by zultron** [comment]
Looks good!  How come that last status isn't finishing?

**Comment by cerna** [comment]
@zultron,
>Looks good! How come that last status isn't finishing?

The same problem as I described in #299:

>The reason why it says Preparatory controlling job Expected — Waiting for status to be reported is because of #298. I shortened the names of individual jobs and to allow to merge I had to change the branch protection rules. (@zultron had issue with name's length in #295, so I further shortened the remaining ones.)

I changed the branch protection rules to require the new name of the first, preparatory job in anticipation of #298 merge - otherwise it would not be mergeable.

(I probably should create an issue about **branch protection rules** and stop playing it in _let and loose_ style. Machinekit is lot more active now than when I first started with it. Then, I could do whatever I pleased, now there are actually other people pushing pull requests.)

**Comment by zultron** [comment]
> The same problem as I described in #299:
> 
> > The reason why it says Preparatory controlling job Expected — Waiting for status to be reported is because of #298.

OK, sorry, I wasn't paying attention when the PR came out of "draft" status.  Merged.

How can we restart the "Preparatory controlling job"?  If it were me, I'd do a `git rebase -f HEAD~ && git push -f`, but maybe there's a simple button somewhere.

**Comment by cerna** [comment]
>How can we restart the "Preparatory controlling job"? If it were me, I'd do a git rebase -f HEAD~ && git push -f, but maybe there's a simple button somewhere.

If there is, I don't know about it. The pull request is build from recipe which is included in the branch that wants to be merged, not from the target branch. So the _"Preparatory controlling job"_ name has to be in `cerna:travis-ci-repair`. I have just rebased on the current master.

**Pull request merged**
