### PR TITLE
Fix build and mksocfpga

### PR DESCRIPTION
**Pull request by the-snowwhite**
Make the Builder build packages again and make Mksocfpga device tree overlay firmware load work again.

### CODE REVIEW

**Comment by cdsteinkuehler** [comment]
Looks OK to me except for the merge conflicts in the debian-distro-settings.json file.  Any chance you can push an update that will resolve the merge conflict?  I don't have a build environment setup currently and am not familiar enough with the json file to want to fix the conflicts by hand w/o a way to test.

**Comment by the-snowwhite** [comment]
@cdsteinkuehler 
The merge conflict was a stray comma I fixed that and for pushed.
All test are passed now..

**Comment by the-snowwhite** [comment]
@cdsteinkuehler Ups I had overlooked the merge conflict fixed now...

**Comment by the-snowwhite** [comment]
@cdsteinkuehler 
I added a fix for the check sometimes not running the curl kitware build cmake stuff properly.
All tests should now pass on first run without the need for rerunning failed checks....

**Comment by the-snowwhite** [comment]
@cdsteinkuehler 
This PR was Intended to replace the former PR that you merged while I was creating this PR.
The merge conflict was due to I had left out Jammy as Jammy has a python 3.10 issue [Python 3.10 incompatibility you can no longer pass a float to an extension function.](https://github.com/machinekit/machinekit-hal/issues/384)

**Pull request merged**
