### PR TITLE
Improve build_with_cnc script

### PR DESCRIPTION
**Pull request by mbuesch**
This pull request adds some checks and convenience things to build_with_cnc.
My goal originally was to also support incremental builds.
However that doesn't seem to work, yet. The cnc build seems to be stuck in an infinite loop. If that problem is found, the make clean can be removed from build_with_cnc again.

### CODE REVIEW

**Comment by ArcEye** [comment]
There is a typo L24: -crc for -cnc

The moving of files common to both scripts/ folders L42: was to prevent problems if you then do a commit or try to build packages and the -cnc copies of the files have changed content and 'pollute' -hal.

It was just a quick fix as they are not required for a RIP, but we should not be overwriting -hal files.

I didn't have problems with any build loops, but I tended just to use the script for the initial build and then go to whichever clone contained what I wanted to change and do it directly, then clean and build that.

**Comment by mbuesch** [comment]
Thanks for your comments.
I fixed the typo.
But I'm not sure whether I understand your comment about the files moved that should not pollute hal.
These two mv's fail (set -e), because the files are actually not there. At that point in the script we are inside of machinekit-crc.
Should I re-add these mv's and first cd to machinekit-hal?

**Comment by ArcEye** [comment]
No, they will only work once with a fresh clone.  As soon as you do an incremental rebuild that command will fail because they only exist in the stash dir.
The script is not a polished item, just something to allow people to build a RIP of both repos without having to think too much about it. :smile: 

Perhaps you could change the lines to
```
mv -f scripts/build_docker scripts/stash > /dev/null 2>&1 ;
mv -f scripts/build_source_package scripts/stash > /dev/null 2>&1 ;
```
and that should take care of failures without raising errors.

**Comment by mbuesch** [comment]
Ah now I got it. :)
What about the changes I just pushed?

**Comment by mbuesch** [comment]
I added another change to avoid surprises if the path contains whitespace.

**Comment by ArcEye** [comment]
Thats a better way to exclude those files without having a long list.
Thanks for your improvements on my very basic linear script.

**Pull request merged**
