### PR TITLE
update halmodule to work work with python3.

### PR DESCRIPTION
**Pull request by rene-dev**
tests pass.
c, tests and python code work with python2 and 3, the build/test system just doesn't support it at the moment.
the way this was fixed in linuxcnc is with a script that executes whatever interpreter was specified during configure.
https://github.com/LinuxCNC/linuxcnc/blob/d7926d868de80c53bd09570c01e53830808f0a76/scripts/linuxcnc-python.in

build using 
`./configure --with-python=python3`

### CODE REVIEW

**Comment by cerna** [comment]
**Few notes:**
- The build/test system is fully integrated into this repository, it has no external elements (theoretically one external component is the Machinekit/Machinekit dependency repository - if you need some special packages there, let me know).

- The C4 rules book mandates that the tests must run green before anything can be merged. In other words, it must be solved in this pull request. (On the other hand, when tests pass [and the change is not trivial like removing the tests] then the pull request must be merged, nobody's opinion is going to prevent this.)

- The problem with build-system will probably be in needed dependency packages (`debian/control.in`), the Debian packages build rules (`debian/rules`) or in RIP-runtester (`debian/ripruntests.py`). Both `.drone/drone.yaml` and `travis.yml` may also need to be changed - given that they are in provisional state.

- The reason why it says _Preparatory controlling job Expected — Waiting for status to be reported_ is because of #298. I shortened the names of individual jobs and to allow to merge I had to change the **branch protection** rules. (@zultron had issue with name's length in #295, so I further shortened the remaining ones.)

**Personal opinions:**

- Drop support for Python 2. It is _EOL_ now and I see no reason why beating dead horse should continue. (Machinekit has precedence with dropping _EOLed_ distributions/technologies, most recently with Debian Jessie.)

- Commits like `90ec34dd50399e998899bab52bd22b298abf94a8` which are no more relevant to the current tree could be maybe dropped?

- The whole Autoconf/make build flow doesn't have to be perfect, given that I am preparing to drop it in #200

**Comment by zultron** [comment]
I submitted a PR against this branch with quick fixes to packaging and cython.  Not well tested, but at least the tests pass.  Very encouraging!

https://github.com/rene-dev/machinekit-hal/pull/1

**Comment by zultron** [comment]
Looking at the commits:
- 3ea650d3:  Hide whitespace changes and this is a lot easier to read
- 2b3b4134:  Ah, no Stretch `py3c-dev` package, just bundle the sources!  We need an issue reminding us to unbundle this down the road (or just fix the C code properly)

Looks great!

**Comment by rene-dev** [comment]
> Looking at the commits:
> 
> * [3ea650d](https://github.com/machinekit/machinekit-hal/commit/3ea650d3770e9df8bf3bb4417363b03d8aacc9e8):  Hide whitespace changes and this is a lot easier to read

whitespace changes are what makes it python3 compatible. python3 disallows mixing tabs and spaces.
> * [2b3b413](https://github.com/machinekit/machinekit-hal/commit/2b3b4134c2b65ec7bbbe18f9511b721f01591c53):  Ah, no Stretch `py3c-dev` package, just bundle the sources!  We need an issue reminding us to unbundle this down the road (or just fix the C code properly)

yes, py3c makes it easier, and we decided to bundle it for linuxcnc, to make it compatible with the ancient distros they use.
its only a few headers.

> 
> Looks great!

**Comment by zultron** [comment]
@rene-dev,
> whitespace changes are what makes it python3 compatible. python3 disallows mixing tabs and spaces.
> 
> yes, py3c makes it easier, and we decided to bundle it for linuxcnc, to make it compatible with the ancient distros they use.
> its only a few headers.

Yes, both totally reasonable.

@cerna, I believe your comments above are all either addressed or easily addressable, except this (which IMO would neaten the stack of commits but the following merges prevent a simple rebase):
>     * Commits like 90ec34dd50399e998899bab52bd22b298abf94a8 which are no more relevant to the current tree could be maybe dropped?

**Comment by zultron** [comment]
I ended up doing a lot of rebasing in [this branch][1], partly to address this comment:

>  * Commits like 90ec34dd which are no more relevant to the current tree could be maybe dropped?

...but also to revert the changes switching `AX_PYTHON_MODULE` back to `AC_PYTHON_MODULE` in 1c8b0b6 (the ` autoconf-archive` package is now listed as a package dep in 6bc019 to fix the build problems).

Then I ran into some problem that made me switch from `dh_python2` to `dh_python3` in the packaging, and this precipitated the need for an avalanche of `.py`-file syntax fixes, since that script compiles `.pyc` files to include in the packaging.  That caused problems in the test scripts, which needed shebangs switched from `python` or `python2` (or `python2.4` :P) to `python3`.  And that in turn prompted more python3 syntax fixes in the test scripts.  Fun stuff, fun stuff.

So now I have a branch that can't really be merged into this very well.  @rene-dev do you want to reset this branch to my tree & force-push, or shall I submit a new PR superseding this one, or what?  My apologies:  I didn't mean to step on your toes or create extra work!

[1]: https://github.com/zultron/machinekit-hal/tree/pr-299-rebase/

**Comment by cerna** [comment]
What one stupid comment can cause...

_Knowing this, I should probably keep my mouth shut, but:_

How big of a problem is the _shebang_ mismatch? Like when I investigated this, the preferred one for Python 3 was something akin to `#!/usr/bin/env python3` - given that one can have different environments and different paths on his system. However, in many places in this code, there are instances of `#!/usr/bin/python3` and similar directly linking to executable.

**Comment by machinekoder** [comment]
@cerna This might indeed become a problem with virtualenv or something similar in use. If it's not too much hassle, I would go for the `env` usage.

**Comment by cerna** [comment]
@zultron,
just a heads up, but I just have noticed, that the branch _zultron:pr-299-rebase_ for some reason is  [failing on armhf in Drone Cloud](https://cloud.drone.io/cerna/machinekit-hal/194/6/3) - and does **regularly**.

**Comment by zultron** [comment]
> @zultron,
> just a heads up, but I just have noticed, that the branch _zultron:pr-299-rebase_ for some reason is [failing on armhf in Drone Cloud](https://cloud.drone.io/cerna/machinekit-hal/194/6/3) - and does **regularly**.

Interesting, it's the `halmodule.0` test.  If we can't hack something in to print out the `result` and `stderr` files in CI, then we'll have to test on native hardware.  I can look at that tomorrow.

**Comment by cerna** [comment]
(_This may be caused by how the Drone workflow is implemented, look down._)

Hmm, 
looking at Drone Cloud, it does provide some output:
```
Running test: /build/machinekit-hal/tests/halmodule.0
--- /build/machinekit-hal/tests/halmodule.0/expected	2020-08-25 18:59:59.317059999 +0000
+++ /build/machinekit-hal/tests/halmodule.0/result	2020-08-25 19:05:04.659002696 +0000
@@ -8,7 +8,7 @@
 set s -2147483648 ok
 set u 0 ok
 set u 1 ok
-set u 4294967295 ok
+set u 4294967295 fail
 set f 0 ok
 set f 0.0 ok
 set f 0 ok
@@ -19,8 +19,8 @@
 set f 1.0 ok
 set f 1 ok
 set f 89884656743115795386465259539451236680898848947115328636715040578866337902750481566354238661203768010560056939935696678829394884407208311246423715319737062188883946712432742638151109800623047059726541476042502884419075341171231440736956555270413618581675255342293149119973622969239858152417678164812112068608 ok
-set s 2147483648 fail
-set s -2147483649 fail
+set s 2147483648 -1
+set s -2147483649 -1
 set u -1 fail
 set u 4294967296 fail
 set f 179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216 fail
*** /build/machinekit-hal/tests/halmodule.0: FAIL: result differed from expected
Running test: /build/machinekit-hal/tests/hm2-idrom
```

However, I discovered that Drone is lying. They say in [documentation](https://docs.drone.io/pipeline/docker/syntax/platform/) that you can specify:
```
platform:
  os: linux
  arch: arm
```
To run on `armhf`, but they don't have the hardware (this is [output run on _arm_](https://cloud.drone.io/cerna/cerna-testing-drone/36/1/2)):
```
+ uname -a
Linux 57041ac8f2e6 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:16 UTC 2018 armv8l GNU/Linux
+ uname -r
4.15.0-34-generic
+ uname -m
armv8l
+ cat /proc/cpuinfo
processor	: 0
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 1
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 2
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 3
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 4
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 5
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 6
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 7
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 8
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 9
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 10
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 11
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 12
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 13
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 14
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 15
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 16
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 17
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 18
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 19
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 20
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 21
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 22
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 23
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 24
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 25
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 26
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 27
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 28
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 29
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 30
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 31
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 32
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 33
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 34
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 35
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 36
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 37
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 38
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 39
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 40
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 41
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 42
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 43
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 44
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 45
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 46
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 47
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 48
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 49
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 50
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 51
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 52
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 53
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 54
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 55
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 56
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 57
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 58
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 59
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 60
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 61
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 62
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 63
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2
```

Which is disappointing. And I will need to look if somebody doesn't have real **arm32/v7** server.

**Comment by zultron** [comment]
> They say in [documentation](https://docs.drone.io/pipeline/docker/syntax/platform/) that you can specify:
> 
> ```
> platform:
>   os: linux
>   arch: arm
> ```
> 
> To run on `armhf`, but they don't have the hardware

So the hardware is 64-bit `armv8l`, but isn't it similiar to 64-bit `x86_64` hardware, which can run 32-bit `i686` binaries identically to 32-bit hardware?  If it's the same with ARM hardware, then the Drone hardware is sufficient.

For testing, 64/32-bit differences are a common source of problems in C programming.  It's very useful that you've added the 32-bit tests.  I suppose it would even be possible to run 32-bit tests on GH Actions with `i686` Docker images, at least for the distros that haven't retired `i686` yet.

**Comment by cerna** [comment]
>So the hardware is 64-bit armv8l, but isn't it similiar to 64-bit x86_64 hardware, which can run 32-bit i686 binaries identically to 32-bit hardware?

Yes, most (if not almost all) `arm64v8`  (64-bit processors) support the 32-bit instructions, so should (are) able to run the `armhf` binaries. In the same way it could be implemented to use the Travis CI _Arm64_ runners. (Which uses LXC, so in all it could be interesting if the problem prevails there too.)

>It's very useful that you've added the 32-bit tests.

I just wanted real hardware. Funny thing is, they even state that, but I was somehow living in the illusion that they state that they have real _arm32v7_ hardware.

>I suppose it would even be possible to run 32-bit tests on GH Actions with i686 Docker images, at least for the distros that haven't retired i686 yet.

That we could and I can implement it easily, I think.

(Well, not that easily, thinking about it. I would need to add different **BUILD** architecture possibility. But maybe it would be a little more robust.)

**Comment by rene-dev** [comment]
superseded by https://github.com/machinekit/machinekit-hal/pull/303

**Pull request closed without merging**
