### PR TITLE
Add Ubuntu Focal to Drone Cloud and Travis CIs

### LINKED ISSUE #302: Support for Debian-like derivative distributions
There is a number of Linux distributions based on Debian and using the _apt_ manager, directly supporting which with Machinekit-HAL packages would not be that hard. Basically, all what is needed is to make sure the Machinekit-HAL binaries build, the dependencies are satisfied and the Docker builder images work (can be build and do not include too much Debian specific parts).

Probably the most viable derivative is the Ubuntu. There are obscure SBCs with patched kernel based on the Ubuntu RT one (_I think_ Jetson Nano is one) and there are applications which target Ubuntu as the primary OS that could benefit from Machinekit integration (like the ROS).

To support Ubuntu, one has to support their _terrible, horrible, no good_ idea of split repositories along the architecture line.

Given that I am currently writing bash script doing exactly that in the Docker builder image's Dockerfile, I would like to open the question if some other derivative should be supported too?

For example, LinuxCNC community likes the Linux Mint.

_(I would like to do it once, do it good and be done with it._)

### PR DESCRIPTION
**Pull request by cerna**
This pull request manually adds the Ubuntu Focal to Drone Cloud CI script and Travis CI script which both run the runtests on supported platforms and build packages on Travis CI to all supported platforms from both `amd64` and `arm64`.

This pull request also contains a script which automagically doctor Docker images on both Debian and Ubuntu for multi-arch build on all supported platforms. (In other words, it adds support for building images for the `arm64`->`amd64` [and so] workflow.)

Change in script's shebang, as discussed in #299, is also added.

Closes #302

### CODE REVIEW

**Comment by cerna** [comment]
Seems like the rules for repository switch don't take in one specific case.

**Comment by zultron** [comment]
Thanks for undoing my `machinekit-fixuid` hack in 870acf9.  I should have looked harder at the problem before putting it into a PR.

There are so many use cases for selecting one of many different installed Python executables (`venv` being an obvious one) that the `#!/usr/bin/env python3` changes seem a necessary eyesore.  However, the parallel `#!/usr/bin/env bash` construction doesn't have a parallel use case, does it?

**Comment by zultron** [comment]
I mistakenly started a review on this, and now can't seem to cancel it.  I'm going to ignore it, but if it turns out to cause problems removing "Draft" status, let me know.

**Comment by cerna** [comment]
>Thanks for undoing my machinekit-fixuid hack in 870acf9. I should have looked harder at the problem before putting it into a PR.

It's not that I want to step on your toes. But user should not be expected to repair package installation. So either the package is faulty which means that it is faulty because of me and I need to check it, or the problem is somewhere else. I ran it through CI multiple times and seen no problem. So I tentatively removed it while waiting if the _"somewhere else"_ will show up.

>However, the parallel #!/usr/bin/env bash construction doesn't have a parallel use case, does it?

I went by [this](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash) thread and [this](https://stackoverflow.com/a/55927235) answer. Basically user can have specific (_patched_) executable in his `PATH` different that the `/bin/bash` one and I assumed that in that case he will want programs to use it. Plus I went with the unification feeling. I can drop it.

>I'm going to ignore it, but if it turns out to cause problems removing "Draft" status, let me know.

I have repaired the script (with a bit more convoluted rules than I would like), so I will try it in a few.

**Comment by zultron** [comment]
> Plus I went with the unification feeling. I can drop it.

Unification is good.  I don't buy the reasoning in those Stackoverflow links, but that's OK.  Don't drop it just for me.  I'll merge when it's ready.

**Comment by cerna** [comment]
>Don't drop it just for me.

Well, turns out it is _yes and no_ situation. After rebasing atop the current master, that commit causes 57 tests to fail. And at the moment I cannot see why. So I dropped it.

Hopefully OK to merge.

>I mistakenly started a review on this, and now can't seem to cancel it.

Turns out force pushing clear it out.

**Pull request merged**
