### PR TITLE
2020 05 08 remove cruft pr

### PR DESCRIPTION
**Pull request by zultron**
Following #279, this is the second of four PRs to support building LCNC-EMC on MK-HAL.

This PR removes a lot of obsolete code:
- Translations for EMC
- A test for EMC
- All remnants of TCL (support for the EMC `hal.so` TCL module will be in the fourth PR)
- `pyvcp` and `gladevcp`  (If this are controversial changes, I can revert)
- `libnml/posemath`

### CODE REVIEW

**Comment by cerna** [comment]
**NOTE TO MAINTAINERS:** Do not merge until all tests and builds on `push` to master (caused by merging #279) are done - even if tests on this pull request finish first.

The build-system (specifically caching of Docker images) currently needs marshalling. (I am open to ideas how to 'asynchrony' it.)

**Comment by zultron** [comment]
Curious, the non-native Jessie builds fail.

I'm SO tempted to remove Jessie support as part of this very PR.

**Comment by cerna** [comment]
> I'm SO tempted to remove Jessie support as part of this very PR.

Then **go** for it.

**Comment by zultron** [comment]
Any idea why the same commit would pass in my [private repo][1], but not here?

[1]:  https://github.com/zultron/machinekit-hal/actions/runs/99121164

**Comment by zultron** [comment]
And, is there any better way to force a rebuild than `git rebase -f HEAD~ && push -f`?

**Comment by cerna** [comment]
> And, is there any better way to force a rebuild than git rebase -f HEAD~ && push -f?

You have finally joined the organization, no? In that case you can `re-run` the **failed** run just by clicking the button in top right corner.

I can implement `repository_dispatch` hook at later date. Then you would just `curl` with **JSON** payload and your **P**ersonal **A**ccess **T**oken.

**Comment by zultron** [comment]
I did join the org, but it seems I don't have some basic privs, like closing out tickets.  I don't see that button, so my `git rebase` hack will have to do for now.

**Comment by cerna** [comment]
@zultron,
> Any idea why the same commit would pass in my private repo, but not here?

OK, so `diff` is zero.

The only thing I see is that in this `pull request`, it is building new Docker image which is then used in all testing and building.

In your linked run, it is using a cached one from your account (probably because you **force** pushed, and currently my system is not liking it). So your last build can have integrated something which newly build one does not have.

**Comment by cerna** [comment]
My cached container [here](https://github.com/cerna/machinekit-hal/runs/656431863?check_suite_focus=true) will also survive it.

(The problem is I cannot get the information needed on force pushes or new branch pushes as these have no **before** SHA referring to some commit in git history.)

**Comment by zultron** [comment]
Interesting.  Thanks for the good clues.  Yes, I'm constantly rebasing and force-pushing.

I'm pretty lost with the `debian-builder-workflow.yaml` so far, so this may have to wait until I find time to catch up.

**Comment by zultron** [comment]
Looking through my reflog, I rebased four times, but each time the diff was zero.  Should that mean that the cached container would be equally applicable to the current revision?

**Comment by cerna** [comment]
The cache container is compromise between building the images on every run (where it will add anything between 10 and 20 minutes of absolute time) and the fact that you cannot delete public Docker images on Github Packages (so I made the call to have `debian-builder-docker-image.${TAG}` with `latest` which will always be rewritten on new push). This is because Github says that there is unlimited space for Open-Source projects, but I don't believe them that they are willing to host terabytes of data nobody really uses.

So new images are rebuild when:

- No images are found in the Github account (or some are missing)
- When changed files reported by git are matching regex `^(scripts/(((containers/){0,1}buildsystem/debian/.{1,})|build_debian_docker_image))|debian/.{1,}$`

Problem is branching and force pushes. Logic so far does not care about different branches. So it will happily use cached Docker image build for another branch. I am planning to solve this by checking if the `vcs-ref` LABEL from Docker image is in checked out git history and maybe even add new LABEL with branch name and then check if this is other branch, then check if changes since this git SHA are matching the regex. On force pushed, I actually don't know what to do. I seem to not be able to get the last SHA common to force pushed branch and that one which was in history before it from GitHub. (There is a possibility to always build on force push, but force pushes are used for rapid development and that is incompatible with added 20 minutes of build time.)

([Logic](https://github.com/machinekit/machinekit-hal/blob/114342866c7fc789b2002e7fa9f82d3cc85d8338/.github/workflows/debian-builder-workflow.yaml#L124-L143).)

> Looking through my reflog, I rebased four times, but each time the diff was zero. Should that mean that the cached container would be equally applicable to the current revision?

It definitely can be. Try forcing rebuild by adding anything to any file in `/debian` folder.

BTW, sorry for the lag. It is nice outside and I need to be putting plants into pots.

**Comment by cerna** [comment]
Hmm, looks like a [hit](https://github.com/zultron/machinekit-hal/actions/runs/99269224).

So next item is to implement dirty branch images flushing, I think.

**Comment by cerna** [comment]
It's the `tests/threads.0` common error. Going to restart.

**Comment by zultron** [comment]
> [...] (There is a possibility to always build on force push, but force pushes are used for rapid development and that is incompatible with added 20 minutes of build time.)

I think it's OK to always build on a force push, because it's more important for CI to be deterministic as possible.  If this had gone the other way around, worst case but entirely possible scenario, we merge a commit where a good, cached container image hides a flaw that builds broken containers, and the problem only shows up after several PRs, causing confusion about where the problem originated.

Help me understand the "rapid development" idea?  In my usual workflow (when I do it right, anyway!), I make a bunch of commits and (non-force) push them; this is my initial "rapid development".  Once CI passes, then I spend time rebasing them to make the submitted PR's commits look more organized for anyone looking, and then force-push; this is my "final polish" mode where I wouldn't mind a longer build at the end.

> It definitely can be. Try forcing rebuild by adding anything to any file in `/debian` folder.

Great, this revealed the problem in the PR branch.

> BTW, sorry for the lag. It is nice outside and I need to be putting plants into pots.

That's exactly what I'd hope you to be doing!  Enjoy.

**Comment by cerna** [comment]
> I think it's OK to always build on a force push, because it's more important for CI to be deterministic as possible. If this had gone the other way around, worst case but entirely possible scenario, we merge a commit where a good, cached container image hides a flaw that builds broken containers, and the problem only shows up after several PRs, causing confusion about where the problem originated.

It cannot go the other way around (I was counting with this possibility [or something like it] in design stage, if it could go that way, it is a bug and my error), because the **C4** states that *Machinekit/Machinekit-HAL* history is written in stone and there is only **one** branch. So everything else is done for better life of forks.

When opening new pull request, if the pull request is not changing any Debian builder Docker images files as specified by the regex, the cached images used are from the **TARGET** (i.e. *Machinekit/Machinekit-HAL*), not from the **SOURCE** (i.e. *${USER}/Machinekit-HAL*). (And when there are no images in **TARGET**, it will act like it changed them.) If pull is not able to build agains the cached images in **TARGET**, well, then it failed. It can either build against existing ones or say it is changing images and build new ones. However, images build during pull request are always trashed. Only during push (merge) the newly build ones are stored in Github Packages.

(This is also reason why I mentioned that pushes should be marshalled one after another and not all in one go.)

So I think it worked correctly and only bitten you. It said it cannot be merged and that was the truth. The reason why it bit you is that I just haven't done it all yet. This *per partes* style I employed of late has a positive that it makes me more active and interested, the whole thing is better tested and change is continuous but it also means not all is 100%. (I quite like it, so not going to change.)

> Help me understand the "rapid development" idea? In my usual workflow (when I do it right, anyway!), I make a bunch of commits and (non-force) push them; this is my initial "rapid development". Once CI passes, then I spend time rebasing them to make the submitted PR's commits look more organized for anyone looking, and then force-push; this is my "final polish" mode where I wouldn't mind a longer build at the end.

I work on `i7-8550U` computer with 32 GB of RAM, in other words, nothing to write home about. On the other hand, you can run 20 concurrent VMs, each with 2 cores and 7 GB, mine for maximum of 6 hours (but then I can just run another). It's easier to just push it to GitHub and run all tests that way than to run it locally (even when I script it, it will be slower).

This is also reason why I want tests on bare metal `arm64` and `armhf`.

I am also trying to avoid force pushing, but usually I forget something or I just don't realize some detail or make a typo. So force pushing is quite common.

**Pull request merged**
