### PR TITLE
Switch to czmq4 API

### PR DESCRIPTION
**Pull request by ArcEye**
Mirrors changes to machinekit repo, with alterations where required.

### CODE REVIEW

**Comment by ArcEye** [comment]
OK, could not remember if the dependencies were pulled per build or hard installed in the /sysroot s
That answers it.
I'll see whether it is better to change the current docker images or wait for @zultron s new ones to come on stream

**Comment by luminize** [comment]
Let me know if you want me to merge.

**Comment by ArcEye** [comment]
Thanks, I have prepared some amended docker images which should build.
Just need to upload those to docker.
Will change the builder to reference them and hopefully it will build.

**Comment by ArcEye** [comment]
OK it has passed, so the full set of packages should build too.

Please merge @luminize

**Comment by ArcEye** [comment]
The main build actually failed, I need to rework the images and try again.
I can restart the build from inside Jenkins, just need to make sure nothing else is merged into this repo until sorted.

**Comment by ArcEye** [comment]
FYI the packages have now been built and any future merges will build properly

The changes to the docker images worked - eventually 😝

**Comment by luminize** [comment]
Thanks @ArcEye !

**Pull request merged**
