### PR TITLE
Document and build system updates for the RPi.

### PR DESCRIPTION
**Pull request by ebo**
I made a number of minor changes to the documentation and build system to get it to work.  I am sending in the changes for a PR now, as it is likely going to be days before I can finish working on the CMakeLists.txt to handle setting the -march robustly.

### CODE REVIEW

**Comment by cerna** [comment]
Hmm, the Github Actions CI needs an approval for first time contributors. That's new.

**Comment by cerna** [comment]
I don't think it can work as it is right now. I hard sets some compile flags in main `CMakeLists.txt` file which are only valid for `arm64` architecture (I think):
```
set(CMAKE_C_FLAGS "-O0 -march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8 ${COMMON_FLAGS}")
```
The architecture specific settings (and settings specific to a platform, i.e. operating system vendor) should be in a toolchain file. (Toolchain files are passed to cmake as `cmake $PATH --toolchain=$TOOLCHAIN_FILE`, more info can be acquired in [documentation](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html).) Machinekit-HAL's toolchain for Debian is in [debianMultiarchToolchain.cmake](https://github.com/machinekit/machinekit-hal/blob/eca0570d9d827dc7b4fcaa029eb8407db0b6e0e1/debian/debianMultiarchToolchain.cmake). (But there could be more.)

I presume that when compiling directly on Raspberry PI, it works, right? And these flags can be used for all `armv8` `arm64` devices, right? So maybe adding an if/switch construct to that Toolchain file would be the best solution.

Now, the configuration step fails on
```
Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_3f9e7/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_3f9e7.dir/build.make CMakeFiles/cmTC_3f9e7.dir/build
gmake[1]: Entering directory '/home/mars/Documents/Programming/machinekit/cmk-hal2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3f9e7.dir/CheckIncludeFile.c.o
/usr/bin/cc   -O0 -march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8   -std=gnu11 -o CMakeFiles/cmTC_3f9e7.dir/CheckIncludeFile.c.o -c /home/mars/Documents/Programming/machinekit/cmk-hal2/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
gmake[1]: *** [CMakeFiles/cmTC_3f9e7.dir/build.make:78: CMakeFiles/cmTC_3f9e7.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory '/home/mars/Documents/Programming/machinekit/cmk-hal2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_3f9e7/fast] Error 2
```

**Comment by ebo** [comment]
As I said the CMakeList.txt file was not ready, but if I did not turn in 
the rest of it now it might be a while before I got to finish it.

**Comment by cerna** [comment]
Interestingly, the error
```
Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_43637/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_43637.dir/build.make CMakeFiles/cmTC_43637.dir/build
gmake[1]: Entering directory '/home/machinekit/m/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_43637.dir/CheckIncludeFile.c.o
/usr/bin/aarch64-linux-gnu-gcc   -O0 -march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8   -std=gnu11 -o CMakeFiles/cmTC_43637.dir/CheckIncludeFile.c.o -c /home/machinekit/m/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mfloat-abi=hard’
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
gmake[1]: *** [CMakeFiles/cmTC_43637.dir/build.make:78: CMakeFiles/cmTC_43637.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory '/home/machinekit/m/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_43637/fast] Error 2
```

shows itself even inside the `machinekit-hal-debian-builder-v.arm64_11:latest` Docker container. (This image is prepared for cross-compiling from `amd64 -> arm64`.)

**Comment by cerna** [comment]
>As I said the CMakeList.txt file was not ready, but if I did not turn in
the rest of it now it might be a while before I got to finish it.

Ah, OK, got it!

**Comment by ebo** [comment]
I'll try to get back to CMakeList.txt again ASAP, but I spent quite some 
time trying to track down how to pull the march, mcpu and other bits 
from the build system to get it right.  I have not seen any exemplar, 
but I was sent some reference documents which will help -- when 
supporting things like the RPi1, Nano, ...

**Comment by ebo** [comment]
@cerna I broke out the documentation edits from the work to get the build system to work as described, and sent another pull request.  I am closing this one.

**Pull request closed without merging**
